import { markRaw } from 'vue'
import ButtonBlockVue from '~~/components/puck/blocks/ButtonBlock.vue'

const buttonIconOptions = [
  { label: 'Tidak ada', value: '' },
  { label: '✓ Check', value: 'pi pi-check' },
  { label: '✕ Times', value: 'pi pi-times' },
  { label: '🔍 Search', value: 'pi pi-search' },
  { label: '🏠 Home', value: 'pi pi-home' },
  { label: '👤 User', value: 'pi pi-user' },
  { label: '⚙ Cog', value: 'pi pi-cog' },
  { label: '📤 Send', value: 'pi pi-send' },
  { label: '🔄 Refresh', value: 'pi pi-refresh' },
  { label: '⬇ Download', value: 'pi pi-download' },
  { label: '⬆ Upload', value: 'pi pi-upload' },
  { label: '+ Plus', value: 'pi pi-plus' },
  { label: '− Minus', value: 'pi pi-minus' },
  { label: '✎ Pencil', value: 'pi pi-pencil' },
  { label: '🗑 Trash', value: 'pi pi-trash' },
  { label: '♥ Heart', value: 'pi pi-heart' },
  { label: '★ Star', value: 'pi pi-star' },
  { label: '🔖 Bookmark', value: 'pi pi-bookmark' },
  { label: '📅 Calendar', value: 'pi pi-calendar' },
  { label: '✉ Envelope', value: 'pi pi-envelope' },
  { label: '📞 Phone', value: 'pi pi-phone' },
  { label: '🔒 Lock', value: 'pi pi-lock' },
  { label: '🔓 Unlock', value: 'pi pi-lock-open' },
  { label: '▶ Play', value: 'pi pi-play' },
  { label: '⏹ Stop', value: 'pi pi-stop' },
  { label: '📋 Copy', value: 'pi pi-copy' },
  { label: '🔗 Link', value: 'pi pi-link' },
  { label: '⋯ Ellipsis', value: 'pi pi-ellipsis-v' },
  { label: '▼ Chevron down', value: 'pi pi-chevron-down' },
  { label: '▲ Chevron up', value: 'pi pi-chevron-up' },
  { label: '◀ Chevron left', value: 'pi pi-chevron-left' },
  { label: '▶ Chevron right', value: 'pi pi-chevron-right' },
]

export const actionsComponents = {
  Button: {
    label: 'Button',
    defaultProps: {
      label: 'Button',
      href: '#',
      severity: 'primary',
      variant: 'filled',
      actionType: 'button',
      buttonType: 'button',
      icon: '',
      iconPos: 'left',
      size: 'normal',
      raised: false,
      rounded: false,
      disabled: false,
      loading: false,
      badge: '',
      badgeSeverity: 'danger',
      ariaLabel: '',
      modalTitle: '',
      modalContentType: 'richtext',
      modalContent: '',
      formId: '',
    },
    fields: {
      label: { type: 'text', label: 'Label', placeholder: 'Lorem ipsum...', contentEditable: true },
      href: { type: 'text', label: 'URL' },
      actionType: {
        type: 'radio',
        label: 'Tipe',
        options: [
          { label: 'Link', value: 'link' },
          { label: 'Button', value: 'button' },
          { label: 'Modal', value: 'modal' },
        ],
      },
      buttonType: {
        type: 'radio',
        label: 'Type (HTML)',
        options: [
          { label: 'button – tombol biasa', value: 'button' },
          { label: 'submit – kirim form', value: 'submit' },
          { label: 'reset – reset form', value: 'reset' },
        ],
      },
      severity: {
        type: 'select',
        label: 'Severity',
        options: [
          { label: 'Primary', value: 'primary' },
          { label: 'Secondary', value: 'secondary' },
          { label: 'Success', value: 'success' },
          { label: 'Info', value: 'info' },
          { label: 'Warn', value: 'warn' },
          { label: 'Help', value: 'help' },
          { label: 'Danger', value: 'danger' },
          { label: 'Contrast', value: 'contrast' },
        ],
      },
      variant: {
        type: 'select',
        label: 'Variant',
        options: [
          { label: 'Filled', value: 'filled' },
          { label: 'Text', value: 'text' },
          { label: 'Outlined', value: 'outlined' },
          { label: 'Link', value: 'link' },
        ],
      },
      icon: { type: 'select', label: 'Icon', options: buttonIconOptions },
      iconPos: {
        type: 'radio',
        label: 'Posisi Icon',
        options: [
          { label: 'Kiri', value: 'left' },
          { label: 'Kanan', value: 'right' },
          { label: 'Atas', value: 'top' },
          { label: 'Bawah', value: 'bottom' },
        ],
      },
      size: {
        type: 'radio',
        label: 'Ukuran',
        options: [
          { label: 'Small', value: 'small' },
          { label: 'Normal', value: 'normal' },
          { label: 'Large', value: 'large' },
        ],
      },
      raised: { type: 'radio', label: 'Raised', options: [{ label: 'Ya', value: true }, { label: 'Tidak', value: false }] },
      rounded: { type: 'radio', label: 'Rounded', options: [{ label: 'Ya', value: true }, { label: 'Tidak', value: false }] },
      disabled: { type: 'radio', label: 'Disabled', options: [{ label: 'Ya', value: true }, { label: 'Tidak', value: false }] },
      loading: { type: 'radio', label: 'Loading', options: [{ label: 'Ya', value: true }, { label: 'Tidak', value: false }] },
      badge: { type: 'text', label: 'Badge (teks, kosongkan jika tidak pakai)' },
      badgeSeverity: {
        type: 'select',
        label: 'Badge Severity',
        options: [
          { label: 'Danger', value: 'danger' },
          { label: 'Contrast', value: 'contrast' },
          { label: 'Primary', value: 'primary' },
          { label: 'Secondary', value: 'secondary' },
        ],
      },
      ariaLabel: { type: 'text', label: 'Aria Label (a11y)' },
      modalTitle: { type: 'text', label: 'Judul Modal' },
      modalContentType: {
        type: 'radio',
        label: 'Konten Modal',
        options: [
          { label: 'Rich Text', value: 'richtext' },
          { label: 'Form', value: 'form' },
        ],
      },
      modalContent: { type: 'richtext', label: 'Konten Modal (Rich Text)' },
      formId: { type: 'text', label: 'ID Form (jika tipe Form)' },
    },
    render: markRaw(ButtonBlockVue),
  },
} as const
