import { markRaw } from 'vue'
import DataTableBlockVue from '~~/components/puck/blocks/DataTableBlock.vue'

export const dataComponents = {
  DataTable: {
    label: 'DataTable',
    defaultProps: {
      columns: [
        { field: 'id', header: 'ID' },
        { field: 'name', header: 'Name' },
        { field: 'email', header: 'Email' },
        { field: 'address.city', header: 'City' },
        { field: 'company.name', header: 'Company' },
      ],
      data: [
        { col1: 'A1', col2: 'B1', _id: 'row-0' },
        { col1: 'A2', col2: 'B2', _id: 'row-1' },
      ],
      apiUrl: '',
      apiDataPath: '',
      apiPageParam: 'page',
      apiLimitParam: 'limit',
      apiTotalPath: 'total',
      paginationMode: 'client',
      paginator: true,
      rows: 10,
      rowsPerPageOptions: [5, 10, 20, 50],
      showGridlines: false,
      stripedRows: true,
      size: 'normal',
      scrollable: false,
      scrollHeight: '400px',
      showRowNumbers: true,
      showActionColumn: true,
      actionButtons: [
        { type: 'edit', label: 'Edit', icon: '✎' },
        { type: 'delete', label: 'Hapus', icon: '🗑' },
      ],
      headerBgColor: '',
      headerTextColor: '',
      bodyBgColor: '',
      bodyZebraColor: '',
      bodyTextColor: '',
      borderColor: '',
      rowHoverColor: '',
      cardTitle: '',
      cardSubtitle: '',
    },
    fields: {
      apiUrl: { type: 'text', label: 'API URL (optional)', description: 'Leave empty for manual data. Example: https://api.example.com/users' },
      apiDataPath: { type: 'text', label: 'API data path', description: 'Path to array in response, e.g. data or results. Leave empty if response is the array.' },
      paginationMode: {
        type: 'radio',
        label: 'Pagination',
        options: [
          { label: 'Client (semua data di-load, potong di UI)', value: 'client' },
          { label: 'Server (fetch per halaman)', value: 'server' },
        ],
      },
      apiPageParam: { type: 'text', label: 'Nama param halaman (server)', description: 'Nama parameter di URL, bukan angkanya. Contoh: page → ?page=1' },
      apiLimitParam: { type: 'text', label: 'Nama param limit (server)', description: 'Nama parameter di URL. Nilai diambil dari "Rows per page". Contoh: limit → ?limit=10' },
      apiTotalPath: { type: 'text', label: 'Path total di response (server)', description: 'Mis. total atau meta.total' },
      columns: {
        type: 'array',
        label: 'Kolom',
        arrayFields: {
          field: {
            type: 'text',
            label: 'Field (key atau path)',
            description: 'Path, atau gabung dengan + . Teks tambahan pakai tanda kutip: address.zipcode + " kodenya " + address.city',
          },
          header: { type: 'text', label: 'Header' },
        },
        defaultItemProps: { field: 'name', header: 'Name' },
      },
      data: {
        type: 'array',
        label: 'Data (manual)',
        arrayFields: {
          col1: { type: 'text', label: 'Kolom 1 (manual)' },
          col2: { type: 'text', label: 'Kolom 2 (manual)' },
          col3: { type: 'text', label: 'Kolom 3 (manual)' },
          col4: { type: 'text', label: 'Kolom 4 (manual)' },
          col5: { type: 'text', label: 'Kolom 5 (manual)' },
        },
        defaultItemProps: { col1: '', col2: '', col3: '', col4: '', col5: '', _id: '' },
      },
      paginator: {
        type: 'radio',
        label: 'Paginator',
        options: [{ label: 'Off', value: false }, { label: 'On', value: true }],
      },
      rows: { type: 'number', label: 'Rows per page', min: 1 },
      showGridlines: {
        type: 'radio',
        label: 'Grid lines',
        options: [{ label: 'Off', value: false }, { label: 'On', value: true }],
      },
      stripedRows: {
        type: 'radio',
        label: 'Striped rows',
        options: [{ label: 'Off', value: false }, { label: 'On', value: true }],
      },
      size: {
        type: 'select',
        label: 'Size',
        options: [
          { label: 'Small', value: 'small' },
          { label: 'Normal', value: 'normal' },
          { label: 'Large', value: 'large' },
        ],
      },
      scrollable: {
        type: 'radio',
        label: 'Scrollable',
        options: [{ label: 'Off', value: false }, { label: 'On', value: true }],
      },
      scrollHeight: { type: 'text', label: 'Scroll height' },
      showRowNumbers: {
        type: 'radio',
        label: 'Kolom No',
        options: [{ label: 'Ya', value: true }, { label: 'Tidak', value: false }],
      },
      headerBgColor: { type: 'color', label: 'Warna header (background)' },
      headerTextColor: { type: 'color', label: 'Warna teks header' },
      bodyBgColor: { type: 'color', label: 'Warna body (background)' },
      bodyZebraColor: { type: 'color', label: 'Warna baris genap (striped)' },
      bodyTextColor: { type: 'color', label: 'Warna teks body' },
      borderColor: { type: 'color', label: 'Warna border' },
      rowHoverColor: { type: 'color', label: 'Warna hover baris' },
      cardTitle: { type: 'text', label: 'Judul card (opsional)' },
      cardSubtitle: { type: 'text', label: 'Subjudul card (opsional)' },
      showActionColumn: {
        type: 'radio',
        label: 'Kolom Aksi',
        options: [{ label: 'Ya', value: true }, { label: 'Tidak', value: false }],
      },
      actionButtons: {
        type: 'array',
        label: 'Tombol aksi (custom)',
        arrayFields: {
          type: {
            type: 'select',
            label: 'Tipe',
            options: [
              { label: 'Edit', value: 'edit' },
              { label: 'Hapus', value: 'delete' },
              { label: 'Link', value: 'link' },
            ],
          },
          label: { type: 'text', label: 'Label (tooltip)' },
          icon: { type: 'text', label: 'Icon (emoji/teks)' },
          url: {
            type: 'text',
            label: 'URL (hanya untuk Link)',
            description: 'Gunakan {{id}} atau {{field}} untuk nilai dari baris. Contoh: /user/{{id}}',
          },
        },
        defaultItemProps: { type: 'edit', label: 'Edit', icon: '✎', url: '' },
      },
    },
    render: markRaw(DataTableBlockVue),
  },
} as const
